export const REGISTER_USER = ` REGISTER_USER`;
export const REGISTER_SUCCESS = `REGISTER_SUCCESS`;
export const REGISTER_FAIL = `REGISTER_FAIL`;

export const LOGIN_USER = `LOGIN_USER`;
export const LOGIN_SUCCESS = `LOGIN_SUCCESS`;
export const LOGIN_FAIL = `LOGIN_FAIL`;

export const GET_PROFILE = `GET_PROFILE`;
export const GET_PROFILE_SUCCESS = `GET_PROFILE_SUCCESS`;
export const GET_PROFILE_FAIL = `GET_PROFILE_FAIL`;

export const ADD_COMMENT = `ADD_COMMENT`;
export const ADD_COMMENT_FAIL = `ADD_COMMENT_FAIL`;
export const ADD_COMMENT_SUCCESS = `ADD_COMMENT_SUCCESS`;


export const UPDATE_USER = `UPDATE_USER`;
export const UPDATE_USER_FAIL = `UPDATE_USER_FAIL`;
export const UPDATE_USER_SUCCESS = `UPDATE_USER_SUCCESS`;


export const GET_ALL_COMMENTS = `GET_ALL_COMMENTS`;
export const GET_ALL_COMMENTS_FAIL = `GET_ALL_COMMENTS_FAIL`;
export const GET_ALL_COMMENTS_SUCCESS = `GET_ALL_COMMENTS_SUCCESS`;

export const GET_ALL_USERS = `GET_ALL_USERS_`;
export const GET_ALL_USERS_FAIL = `GET_ALL_USERS_FAIL`;
export const GET_ALL_USERS_SUCCESS = `GET_ALL_USERS_SUCCESS`;


export const DELETE_USER = `DELETE_USER`;
export const DELETE_USER_FAIL = `DELETE_USER_FAIL`;
export const DELETE_USER_SUCCESS = `DELETE_USER_SUCCESS`;

export const DELETE_COMMENT = `DELETE_COMMENT`;
export const DELETE_COMMENT_FAIL = `DELETE_COMMENT_FAIL`;
export const DELETE_COMMENT_SUCCESS = `DELETE_COMMENT_SUCCESS`;

export const GET_ONE_USER = `GET_ONE_USER`;
export const GET_ONE_USER_FAIL = `GET_ONE_USER_FAIL`;
export const GET_ONE_USER_SUCCESS = `GET_ONE_USER_SUCCESS`;


export const LOGOUT = `LOGOUT`;